image: registry.csc.sibsutis.ru/ci/git-clang-format:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - make && make run

test:
  stage: test
  script:
    - make test && make run_test